- name: 11-Download nginx with version 1.18.0 in "{{ download_dir }}"
  get_url:
    url: "{{ nginx_url }}"
    dest: "{{ download_dir }}"

- name: 11.1-Extract nginx-1.18.0.tar.gz into "{{ download_dir }}"
  ansible.builtin.unarchive:
    src: "{{ download_dir }}{{ nginx_file_name }}"
    dest: "{{ download_dir }}"
    remote_src: yes

- name: 11.2-Configuration of nginx with module ModSecurity-nginx
  args:
    chdir: "{{ nginx_folder }}"
    executable: "/bin/bash"
  shell: |
    ./configure --with-compat --add-dynamic-module=../ModSecurity-nginx
    make modules
    cp objs/ngx_http_modsecurity_module.so /usr/share/nginx/modules/