- name: 8-Install ModSecurity from directory {{ git_dest_folder_ModSecurity }}
  args:
    chdir: "{{ git_dest_folder_ModSecurity }}"
    executable: "/bin/bash"
  shell: |
    git submodule init 
    git submodule update 
    sh build.sh 
    ./configure 
    make
    make install
